# Generated by Django 2.0.2 on 2020-07-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdopedido',
            name='desconto',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
