# Generated by Django 2.0.2 on 2020-09-03 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20200810_0716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuario pode alterar parametro NF-e'), ('permissao2', 'Permissão 2'), ('permissao3', 'Permissão 3'))},
        ),
    ]
